services:
  database:
    image: postgres:18.1-bookworm
    container_name: database-dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata-dev:/var/lib/postgresql
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server-dev
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
    volumes:
      - ./server:/server # Mount source code for live reloading
      - go-modules:/go/pkg/mod # Cache Go modules
    expose:
      - "3000"
    depends_on:
      - database
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin-dev
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      - database
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web-dev
    restart: unless-stopped
    ports:
      - "8080:80" # Different port for dev to avoid conflicts
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata-dev:
  go-modules:
